/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cz.akarienta.fakturator;

import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author akarienta
 */
public class GUI extends javax.swing.JFrame {
    
    private static final List<JPanel> panels = new ArrayList<JPanel>();
    private static final List<String> customers = new ArrayList<String>();
    static {
        customers.add("Test1");
        customers.add("Test2");
    }
    
    private int rowId;

    /**
     * Creates new form gui
     */
    public GUI() {
        initComponents();
        buildPanels();
        switchToPanel(welcomePanel);
        customerList.setModel(new DefaultComboBoxModel());
            for (String customer : customers) {
            customerList.addItem(customer);
        }          
        clearNewInvoicePanel();
    }
    
    private void buildPanels() {
        panels.add(welcomePanel);
        panels.add(newInvoicePanel);
        panels.add(contractorPanel);
    }
    
    private void hideAllPanels() {
        for(JPanel panel : panels) {
            panel.setVisible(false);
        }
    }
    
    private void switchToPanel(JPanel panel) {
        hideAllPanels();
        panel.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        welcomePanel = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        appName = new javax.swing.JLabel();
        newInvoicePanel = new javax.swing.JPanel();
        customer = new javax.swing.JLabel();
        invoiceNumber = new javax.swing.JLabel();
        customerList = new javax.swing.JComboBox();
        invoiceNumberField = new javax.swing.JTextField();
        dateOfIssue = new javax.swing.JLabel();
        dateOfValidity = new javax.swing.JLabel();
        dateOfIssueField = new javax.swing.JTextField();
        dateOfValidtyField = new javax.swing.JTextField();
        newItemHeadline = new javax.swing.JLabel();
        itemName = new javax.swing.JLabel();
        itemPrice = new javax.swing.JLabel();
        itemNameField = new javax.swing.JTextField();
        itemPriceField = new javax.swing.JTextField();
        tablePanel = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        addItem = new javax.swing.JButton();
        deleteItemHeadline = new javax.swing.JLabel();
        currency = new javax.swing.JLabel();
        itemIdField = new javax.swing.JTextField();
        itemId = new javax.swing.JLabel();
        deleteItem = new javax.swing.JButton();
        printInvoice = new javax.swing.JToggleButton();
        notification = new javax.swing.JLabel();
        userAsInvoiceNumber = new javax.swing.JCheckBox();
        contractorPanel = new javax.swing.JPanel();
        contractorName = new javax.swing.JLabel();
        contractorNameField = new javax.swing.JTextField();
        contractorAddress = new javax.swing.JLabel();
        contractorAddressField = new javax.swing.JTextField();
        contractorCity = new javax.swing.JLabel();
        contractorPostalCode = new javax.swing.JLabel();
        contractorIco = new javax.swing.JLabel();
        contractorBank = new javax.swing.JLabel();
        contractorAccountNumber = new javax.swing.JLabel();
        contractorPhone = new javax.swing.JLabel();
        contractorMail = new javax.swing.JLabel();
        contractorWeb = new javax.swing.JLabel();
        contractorCityField = new javax.swing.JTextField();
        contractorIcoField = new javax.swing.JTextField();
        contractorPostalCodeField = new javax.swing.JTextField();
        contractorBankField = new javax.swing.JTextField();
        contractorAccountNumberField = new javax.swing.JTextField();
        contractorPhoneField = new javax.swing.JTextField();
        contractorMialField = new javax.swing.JTextField();
        contractorWebField = new javax.swing.JTextField();
        contractorSignatureFile = new javax.swing.JLabel();
        contractorSignatureFileField = new javax.swing.JTextField();
        contractorSave = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        contractorNameNote = new javax.swing.JLabel();
        contractorBankNote = new javax.swing.JLabel();
        contractorAccountNumberNote = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        menu = new javax.swing.JMenuBar();
        file = new javax.swing.JMenu();
        newInvoice = new javax.swing.JMenuItem();
        settings = new javax.swing.JMenu();
        contractor = new javax.swing.JMenuItem();
        customerEntry = new javax.swing.JMenuItem();
        help = new javax.swing.JMenu();
        about = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Fakturator");
        setMaximumSize(new java.awt.Dimension(784, 620));
        setMinimumSize(new java.awt.Dimension(784, 620));
        setName("mainFrame"); // NOI18N
        setPreferredSize(new java.awt.Dimension(784, 620));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        welcomePanel.setMaximumSize(new java.awt.Dimension(780, 620));
        welcomePanel.setMinimumSize(new java.awt.Dimension(780, 620));
        welcomePanel.setPreferredSize(new java.awt.Dimension(780, 620));
        welcomePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cz/akarienta/fakturator/img/logo.png"))); // NOI18N
        welcomePanel.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, -1, -1));

        appName.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 48)); // NOI18N
        appName.setText("Fakturator");
        welcomePanel.add(appName, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 250, -1, 47));

        getContentPane().add(welcomePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 620));

        newInvoicePanel.setMaximumSize(new java.awt.Dimension(780, 600));
        newInvoicePanel.setMinimumSize(new java.awt.Dimension(780, 600));
        newInvoicePanel.setPreferredSize(new java.awt.Dimension(780, 600));

        customer.setText("Odběratel");

        invoiceNumber.setText("Číslo dokladu");

        customerList.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        invoiceNumberField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                invoiceNumberFieldActionPerformed(evt);
            }
        });

        dateOfIssue.setText("Datum vystavení");

        dateOfValidity.setText("Datum splatnosti");

        newItemHeadline.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        newItemHeadline.setText("Nová položka");

        itemName.setText("Název");

        itemPrice.setText("Cena");

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Název", "Cena (Kč)"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablePanel.setViewportView(table);
        if (table.getColumnModel().getColumnCount() > 0) {
            table.getColumnModel().getColumn(0).setResizable(false);
            table.getColumnModel().getColumn(0).setPreferredWidth(20);
            table.getColumnModel().getColumn(1).setResizable(false);
            table.getColumnModel().getColumn(1).setPreferredWidth(500);
            table.getColumnModel().getColumn(2).setResizable(false);
            table.getColumnModel().getColumn(2).setPreferredWidth(100);
        }

        addItem.setText("Přidat");
        addItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addItemActionPerformed(evt);
            }
        });

        deleteItemHeadline.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        deleteItemHeadline.setText("Smazat položku");

        currency.setText("Kč");

        itemId.setText("ID");

        deleteItem.setText("Smazat");
        deleteItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteItemActionPerformed(evt);
            }
        });

        printInvoice.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        printInvoice.setText("VYSTAVIT FAKTURU");
        printInvoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printInvoiceActionPerformed(evt);
            }
        });

        notification.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N

        userAsInvoiceNumber.setText("použít pro číslování");

        javax.swing.GroupLayout newInvoicePanelLayout = new javax.swing.GroupLayout(newInvoicePanel);
        newInvoicePanel.setLayout(newInvoicePanelLayout);
        newInvoicePanelLayout.setHorizontalGroup(
            newInvoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tablePanel)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, newInvoicePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(newInvoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(notification, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, newInvoicePanelLayout.createSequentialGroup()
                        .addGroup(newInvoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dateOfIssue)
                            .addComponent(invoiceNumber, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addGroup(newInvoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dateOfIssueField, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(newInvoicePanelLayout.createSequentialGroup()
                                .addComponent(invoiceNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(userAsInvoiceNumber)))
                        .addGap(49, 49, 49)
                        .addGroup(newInvoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(newInvoicePanelLayout.createSequentialGroup()
                                .addComponent(dateOfValidity)
                                .addGap(18, 18, 18)
                                .addComponent(dateOfValidtyField, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(newInvoicePanelLayout.createSequentialGroup()
                                .addComponent(customer)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(customerList, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, newInvoicePanelLayout.createSequentialGroup()
                        .addGroup(newInvoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(newInvoicePanelLayout.createSequentialGroup()
                                .addGroup(newInvoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(itemName)
                                    .addComponent(itemPrice))
                                .addGap(18, 18, 18)
                                .addGroup(newInvoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(newInvoicePanelLayout.createSequentialGroup()
                                        .addComponent(itemPriceField, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(3, 3, 3)
                                        .addComponent(currency)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(addItem, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(itemNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(newItemHeadline))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(newInvoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(deleteItemHeadline, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(newInvoicePanelLayout.createSequentialGroup()
                                .addComponent(itemId)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(itemIdField, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(deleteItem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
            .addGroup(newInvoicePanelLayout.createSequentialGroup()
                .addGap(234, 234, 234)
                .addComponent(printInvoice, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        newInvoicePanelLayout.setVerticalGroup(
            newInvoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newInvoicePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(notification)
                .addGap(13, 13, 13)
                .addGroup(newInvoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(invoiceNumber)
                    .addComponent(invoiceNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(customer)
                    .addComponent(customerList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userAsInvoiceNumber))
                .addGap(9, 9, 9)
                .addGroup(newInvoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(newInvoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(dateOfValidtyField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(dateOfValidity))
                    .addGroup(newInvoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(dateOfIssueField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(dateOfIssue)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(newInvoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newItemHeadline)
                    .addComponent(deleteItemHeadline))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(newInvoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(itemName)
                    .addComponent(itemNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(itemIdField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(itemId))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(newInvoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(itemPrice)
                    .addComponent(itemPriceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(currency)
                    .addComponent(addItem)
                    .addComponent(deleteItem))
                .addGap(18, 18, 18)
                .addComponent(tablePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(printInvoice, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        getContentPane().add(newInvoicePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 600));

        contractorPanel.setMaximumSize(new java.awt.Dimension(780, 600));
        contractorPanel.setMinimumSize(new java.awt.Dimension(780, 600));
        contractorPanel.setPreferredSize(new java.awt.Dimension(780, 600));

        contractorName.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        contractorName.setText("Jméno");

        contractorAddress.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        contractorAddress.setText("Ulice a číslo popisné/orientační");

        contractorCity.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        contractorCity.setText("Město");

        contractorPostalCode.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        contractorPostalCode.setText("PSČ");

        contractorIco.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        contractorIco.setText("IČ");

        contractorBank.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        contractorBank.setText("Banka");

        contractorAccountNumber.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        contractorAccountNumber.setText("Číslo účtu");

        contractorPhone.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        contractorPhone.setText("Telefon");

        contractorMail.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        contractorMail.setText("E-mail");

        contractorWeb.setText("Web");

        contractorSignatureFile.setText("Obrázek podpisu");

        contractorSave.setText("Uložit údaje");

        jLabel1.setText("* tučně vyznačené údaje je nutné vyplnit");

        contractorNameNote.setFont(new java.awt.Font("Cantarell", 2, 15)); // NOI18N
        contractorNameNote.setText("včetně příp. titulů a prostředního jména");

        contractorBankNote.setFont(new java.awt.Font("Cantarell", 2, 15)); // NOI18N
        contractorBankNote.setText("název Vaší banky");

        contractorAccountNumberNote.setFont(new java.awt.Font("Cantarell", 2, 15)); // NOI18N
        contractorAccountNumberNote.setText("včetně kódu banky");

        jButton1.setText("Procházet...");

        javax.swing.GroupLayout contractorPanelLayout = new javax.swing.GroupLayout(contractorPanel);
        contractorPanel.setLayout(contractorPanelLayout);
        contractorPanelLayout.setHorizontalGroup(
            contractorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contractorPanelLayout.createSequentialGroup()
                .addGroup(contractorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contractorPanelLayout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addGroup(contractorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(contractorAccountNumber)
                            .addComponent(contractorBank)
                            .addComponent(contractorPhone)
                            .addComponent(contractorMail)
                            .addComponent(contractorPostalCode)
                            .addComponent(contractorIco)
                            .addComponent(contractorWeb)
                            .addComponent(contractorSignatureFile))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(contractorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(contractorPanelLayout.createSequentialGroup()
                                .addGroup(contractorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(contractorSignatureFileField, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(contractorIcoField, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(contractorBankField, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(contractorAccountNumberField, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(contractorPhoneField, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(contractorMialField, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(contractorWebField, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(contractorPostalCodeField, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(contractorSave, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(contractorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(contractorBankNote)
                                    .addComponent(contractorAccountNumberNote)
                                    .addComponent(jButton1)))))
                    .addGroup(contractorPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(contractorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(contractorName)
                            .addComponent(contractorAddress)
                            .addComponent(contractorCity))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(contractorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(contractorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(contractorAddressField, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
                                .addComponent(contractorCityField))
                            .addGroup(contractorPanelLayout.createSequentialGroup()
                                .addComponent(contractorNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(contractorNameNote)))))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        contractorPanelLayout.setVerticalGroup(
            contractorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contractorPanelLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(contractorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contractorName)
                    .addComponent(contractorNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(contractorNameNote))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(contractorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contractorAddressField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(contractorAddress))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(contractorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contractorCityField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(contractorCity))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(contractorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contractorPostalCodeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(contractorPostalCode))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(contractorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contractorIcoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(contractorIco))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(contractorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contractorBankField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(contractorBank)
                    .addComponent(contractorBankNote))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(contractorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contractorAccountNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(contractorAccountNumber)
                    .addComponent(contractorAccountNumberNote))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(contractorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contractorPhoneField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(contractorPhone))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(contractorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contractorMialField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(contractorMail))
                .addGap(10, 10, 10)
                .addGroup(contractorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contractorWebField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(contractorWeb))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(contractorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contractorSignatureFileField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(contractorSignatureFile)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addGap(12, 12, 12)
                .addComponent(contractorSave)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(contractorPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 600));

        file.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cz/akarienta/fakturator/img/house.png"))); // NOI18N
        file.setText("Soubor");

        newInvoice.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        newInvoice.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cz/akarienta/fakturator/img/file-text.png"))); // NOI18N
        newInvoice.setText("Nová faktura");
        newInvoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newInvoiceActionPerformed(evt);
            }
        });
        file.add(newInvoice);

        menu.add(file);

        settings.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cz/akarienta/fakturator/img/wrench-screwdriver.png"))); // NOI18N
        settings.setText("Nastavení");

        contractor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.SHIFT_MASK));
        contractor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cz/akarienta/fakturator/img/user-male.png"))); // NOI18N
        contractor.setText("Dodavatel");
        contractor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contractorActionPerformed(evt);
            }
        });
        settings.add(contractor);

        customerEntry.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.SHIFT_MASK));
        customerEntry.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cz/akarienta/fakturator/img/address-book-alt.png"))); // NOI18N
        customerEntry.setText("Odběratelé");
        settings.add(customerEntry);

        menu.add(settings);

        help.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cz/akarienta/fakturator/img/life-buoy.png"))); // NOI18N
        help.setText("Nápověda");

        about.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        about.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cz/akarienta/fakturator/img/light-bulb.png"))); // NOI18N
        about.setText("O programu");
        help.add(about);

        menu.add(help);

        setJMenuBar(menu);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void invoiceNumberFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_invoiceNumberFieldActionPerformed
	// TODO
    }//GEN-LAST:event_invoiceNumberFieldActionPerformed

    private void printInvoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printInvoiceActionPerformed
	// TODO
    }//GEN-LAST:event_printInvoiceActionPerformed

    private void newInvoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newInvoiceActionPerformed
        switchToPanel(newInvoicePanel);
    }//GEN-LAST:event_newInvoiceActionPerformed

    private void addItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addItemActionPerformed
        addItem();
    }//GEN-LAST:event_addItemActionPerformed

    private void deleteItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteItemActionPerformed
        removeItem();
    }//GEN-LAST:event_deleteItemActionPerformed

    private void contractorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contractorActionPerformed
        switchToPanel(contractorPanel);
    }//GEN-LAST:event_contractorActionPerformed

    private void addItem() {
        String itemNameText = itemNameField.getText();
        String priceText = itemPriceField.getText();
        if (isEmpty(itemName.getText(), itemNameText)) return;
        if (isEmpty(itemPrice.getText(), priceText)) return;
        
        Double price = stringToDouble(itemPrice.getText(), priceText);
        if (price == null) return;
        
        DefaultTableModel model = (DefaultTableModel) table.getModel();
        
        Object[] row = {this.rowId, itemNameText, price};

        model.addRow(row);
        table.setModel(model);
        
        this.rowId++;
        clearNewInvoicePanel();
    }
    
    private void removeItem() {
        String idText = itemIdField.getText();
        if(isEmpty(itemId.getText(), idText)) return;
        
        Integer id = stringToInteger(itemId.getText(), idText);
        if (id == null) return;
        
        DefaultTableModel model = (DefaultTableModel) table.getModel();
        
        for (int i = 0; i < model.getRowCount(); i++) {
            if (model.getValueAt(i, 0) == id) {
                model.removeRow(i);
                clearNewInvoicePanel();
                return;
            } 
        }
        setError("Položka s ID " + id + " neexistuje.");
    }
    
    private Double stringToDouble(String valueName, String value) {
        String czDecimalFormat = value.replace(",", ".");
        Double result = null;
        try {
           result = Double.parseDouble(czDecimalFormat);
        } catch (NumberFormatException ex) {
            setError("Hodnota '" + valueName + "' musí být desetinné číslo.");
        }
        return result;
    }
    
    private Integer stringToInteger(String valueName, String value) {
        Integer result = null;
        try {
           result = Integer.parseInt(value);
        } catch (NumberFormatException ex) {
            setError("Hodnota '" + valueName + "' musí být celé číslo.");
        }
        return result;
    }
    
    private void setError(String errorMsg) {
        notification.setForeground(new java.awt.Color(205, 10, 0));
        notification.setText("CHYBA: " + errorMsg);
    }
    
    private void setInfo(String errorMsg) {
        notification.setForeground(new java.awt.Color(2, 159, 9));
        notification.setText("INFO: " + errorMsg);
    }
    
    private void clearNewInvoicePanel() {
        notification.setText("");
        itemNameField.setText("");
        itemPriceField.setText("");
        itemIdField.setText("");
    }
    
    private boolean isEmpty(String valueName, String value) {
        if ("".equals(value)) {
            setError("Hodnota '" + valueName + "' musí být vyplněna a není.");
            return true;
        } else {
            return false;
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem about;
    private javax.swing.JButton addItem;
    private javax.swing.JLabel appName;
    private javax.swing.JMenuItem contractor;
    private javax.swing.JLabel contractorAccountNumber;
    private javax.swing.JTextField contractorAccountNumberField;
    private javax.swing.JLabel contractorAccountNumberNote;
    private javax.swing.JLabel contractorAddress;
    private javax.swing.JTextField contractorAddressField;
    private javax.swing.JLabel contractorBank;
    private javax.swing.JTextField contractorBankField;
    private javax.swing.JLabel contractorBankNote;
    private javax.swing.JLabel contractorCity;
    private javax.swing.JTextField contractorCityField;
    private javax.swing.JLabel contractorIco;
    private javax.swing.JTextField contractorIcoField;
    private javax.swing.JLabel contractorMail;
    private javax.swing.JTextField contractorMialField;
    private javax.swing.JLabel contractorName;
    private javax.swing.JTextField contractorNameField;
    private javax.swing.JLabel contractorNameNote;
    private javax.swing.JPanel contractorPanel;
    private javax.swing.JLabel contractorPhone;
    private javax.swing.JTextField contractorPhoneField;
    private javax.swing.JLabel contractorPostalCode;
    private javax.swing.JTextField contractorPostalCodeField;
    private javax.swing.JToggleButton contractorSave;
    private javax.swing.JLabel contractorSignatureFile;
    private javax.swing.JTextField contractorSignatureFileField;
    private javax.swing.JLabel contractorWeb;
    private javax.swing.JTextField contractorWebField;
    private javax.swing.JLabel currency;
    private javax.swing.JLabel customer;
    private javax.swing.JMenuItem customerEntry;
    private javax.swing.JComboBox customerList;
    private javax.swing.JLabel dateOfIssue;
    private javax.swing.JTextField dateOfIssueField;
    private javax.swing.JLabel dateOfValidity;
    private javax.swing.JTextField dateOfValidtyField;
    private javax.swing.JButton deleteItem;
    private javax.swing.JLabel deleteItemHeadline;
    private javax.swing.JMenu file;
    private javax.swing.JMenu help;
    private javax.swing.JLabel invoiceNumber;
    private javax.swing.JTextField invoiceNumberField;
    private javax.swing.JLabel itemId;
    private javax.swing.JTextField itemIdField;
    private javax.swing.JLabel itemName;
    private javax.swing.JTextField itemNameField;
    private javax.swing.JLabel itemPrice;
    private javax.swing.JTextField itemPriceField;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel logo;
    private javax.swing.JMenuBar menu;
    private javax.swing.JMenuItem newInvoice;
    private javax.swing.JPanel newInvoicePanel;
    private javax.swing.JLabel newItemHeadline;
    private javax.swing.JLabel notification;
    private javax.swing.JToggleButton printInvoice;
    private javax.swing.JMenu settings;
    private javax.swing.JTable table;
    private javax.swing.JScrollPane tablePanel;
    private javax.swing.JCheckBox userAsInvoiceNumber;
    private javax.swing.JPanel welcomePanel;
    // End of variables declaration//GEN-END:variables
}
